import {
  cmp, each,
  File, Content, Copy, Folder,
} from '@voxgig/sdkgen'


import type {
  ModelEntity
} from '@voxgig/apidef'


import {
  KIT,
  getModelPath
} from '@voxgig/apidef'


import { Package } from './Package_haskell'
import { Config } from './Config_haskell'
import { Gitignore } from './Gitignore_haskell'
import { hsVarName } from './utility_haskell'


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  Package({ target })

  Gitignore({})

  // Copy tm/haskell verbatim: the runtime under src/ (VoxgigStruct, Vregex,
  // SdkTypes, SdkHelpers, SdkRuntime, SdkFeatures), the test suite under
  // test/, and Makefile/LICENSE/VERSION. The per-feature custom-source
  // scaffold under src/feature is excluded (this target does not use it —
  // entities are generic and config-driven, so there are no per-entity or
  // per-feature generated modules). Placeholder substitution applies.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\/feature\//],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  // Generated modules under src/: the API config + feature factory, and the
  // public client (SDK constructors + entity accessors).
  Folder({ name: 'src' }, () => {

    Config({ target })

    File({ name: 'SdkClient.' + target.ext }, () => {

      let accessors = ''
      let exports = ''
      each(entity, (e: any) => {
        const fn = hsVarName(e.name)
        exports += `  , ${fn}\n`
        accessors += `-- | The ${e.Name} entity bound to this client.
${fn} :: Client -> Value -> IO Entity
${fn} client entopts = F.makeEntity client "${e.name}" entopts

`
      })

      Content(`-- ${model.const.Name} SDK public client (generated by @voxgig/sdkgen).
--
-- SDK constructors (newSdk / testSdk) and one accessor per entity. Entities
-- are generic — every accessor calls the config-driven F.makeEntity, so the
-- operation pipeline is identical for every entity and every API.

module SdkClient
  ( module SdkTypes
  , newSdk
  , newSdk0
  , testSdk
  , testSdk0
${exports}  ) where

import Data.IORef (readIORef)

import VoxgigStruct (Value (..))
import SdkTypes
import SdkConfig (makeConfig, makeFeature)
import qualified SdkFeatures as F

-- | Construct a live SDK client from an options map (Noval for defaults).
newSdk :: Value -> IO Client
newSdk options = do
  cfg <- makeConfig
  F.makeClientBase cfg makeFeature options

-- | No-argument convenience constructor.
newSdk0 :: IO Client
newSdk0 = newSdk VNoval

-- | Construct a test-mode SDK: testSdk testopts sdkopts.
testSdk :: Value -> Value -> IO Client
testSdk testopts sdkopts = do
  cfg <- makeConfig
  F.sdkTest cfg makeFeature testopts sdkopts

-- | No-argument convenience test constructor.
testSdk0 :: IO Client
testSdk0 = testSdk VNoval VNoval

-- | The active client mode ("live" or "test").
clientMode :: Client -> IO String
clientMode = readIORef . clMode

${accessors}`)
    })
  })

})


export {
  Main
}
