import {
  Content,
  File,
  cmp,
  packageVersion,
} from '@voxgig/sdkgen'


import type {
  Model,
} from '@voxgig/apidef'


function pkgName(model: any): string {
  const org = (model.origin || 'voxgig-sdk').replace(/-sdk$/, '')
  return `${org}-${model.name}-sdk`.toLowerCase().replace(/[^a-z0-9-]/g, '-')
}


// The cabal package file (for Hackage publication). The offline test build
// uses the Makefile (stock ghc, boot libraries only: base + containers +
// array + time), so no cabal solve is required to run the suite.
const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target

  const model: Model = ctx$.model

  File({ name: pkgName(model) + '.cabal' }, () => {
    Content(`cabal-version:      2.4
name:               ${pkgName(model)}
version:            ${packageVersion(model, target.name)}
synopsis:           ${model.const.Name} SDK for Haskell (generated by @voxgig/sdkgen)
license:            MIT
build-type:         Simple

library
    default-language: Haskell2010
    hs-source-dirs:   src
    exposed-modules:  VoxgigStruct
                      Vregex
                      SdkJson
                      SdkTypes
                      SdkHelpers
                      SdkRuntime
                      SdkFeatures
                      SdkConfig
                      SdkClient
    build-depends:    base >=4.14 && <5
                    , containers >=0.6 && <0.8
                    , array >=0.5 && <0.6
                    , time >=1.9 && <1.15
`)
  })
})


export {
  Package
}
