
import { cmp, File, Content } from '@voxgig/sdkgen'


const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name

  File({ name: 'TReadmeExamples.' + target.ext }, () => {
    Content(`-- ${Name} SDK — documentation Haskell-examples structural gate.
--
-- Validates that every fenced Haskell code block in the SDK docs (the root
-- README.md, the per-language README.md, and REFERENCE.md) is present,
-- non-empty, and has balanced delimiters. Missing docs are tolerated (a run
-- may generate a subset of phases), but a doc that exists and cannot be read
-- fails. See ReadmeExamplesTest_haskell for why this is a structural gate
-- rather than a full compile harness. Generated by @voxgig/sdkgen.

{-# LANGUAGE ScopedTypeVariables #-}

module TReadmeExamples (tests) where

import Control.Monad (forM_)
import System.IO.Error (isDoesNotExistError, tryIOError)

import Testutil (Counters, readUtf8, runTest)


-- True for the whitespace characters we trim: space, tab, carriage return.
isWs :: Char -> Bool
isWs ch = let n = fromEnum ch in n == 32 || n == 9 || n == 13


-- Trim leading/trailing whitespace from a line.
trimWs :: String -> String
trimWs = f . f
  where f = reverse . dropWhile isWs


-- A doc's text, "" when it is absent, or why an existing doc cannot be read.
readDoc :: FilePath -> IO (Either String String)
readDoc path = do
  r <- tryIOError (readUtf8 path)
  pure (case r of
    Right s -> Right s
    Left e | isDoesNotExistError e -> Right ""
           | otherwise -> Left (show e))


-- Extract the body of every fenced Haskell block from markdown. Returns
-- (blocks, allClosed) where allClosed is False when a fence was opened but
-- never closed before EOF — a malformed doc that must fail rather than pass
-- silently on the unterminated block. The fence marker (three backticks) is
-- built from its char code so this source stays backtick-free.
haskellBlocks :: String -> ([String], Bool)
haskellBlocks src = go (lines src)
  where
    fence3 = replicate 3 (toEnum 96 :: Char)
    fenceHs = fence3 ++ "haskell"
    go [] = ([], True)
    go (l : ls)
      | trimWs l == fenceHs =
          case break (\\x -> trimWs x == fence3) ls of
            (blk, [])       -> ([unlines blk], False)
            (blk, _ : rest) -> let (bs, ok) = go rest in (unlines blk : bs, ok)
      | otherwise = go ls


-- Balanced (), [], {} outside of double-quoted string literals, with each
-- closer matching the most-recent opener via a stack (so "([)]" is rejected,
-- not merely counted). The generated snippets never embed an escaped quote
-- inside a string.
balanced :: String -> Bool
balanced = go False []
  where
    go inStr stack [] = not inStr && null stack
    go inStr stack (c : cs)
      | c == '"'                          = go (not inStr) stack cs
      | inStr                             = go inStr stack cs
      | c == '('                          = go inStr (')' : stack) cs
      | c == '['                          = go inStr (']' : stack) cs
      | c == '{'                          = go inStr ('}' : stack) cs
      | c == ')' || c == ']' || c == '}'  =
          case stack of
            (top : rest) | top == c -> go inStr rest cs
            _                        -> False
      | otherwise                         = go inStr stack cs


-- The three documents held to the gate, tagged by human label.
docs :: [(String, FilePath)]
docs =
  [ ("root README", "../README.md")
  , ("${target.name} README", "README.md")
  , ("${target.name} REFERENCE", "REFERENCE.md")
  ]


tests :: Counters -> IO ()
tests c =
  forM_ docs (\\(label, path) -> do
    doc <- readDoc path
    case doc of
      Left err -> runTest c (label ++ " readable (" ++ err ++ ")") (pure False)
      Right src -> do
        let (blocks, closed) = haskellBlocks src
        runTest c (label ++ " haskell fences closed") (pure closed)
        forM_ (zip [1 :: Int ..] blocks) (\\(i, blk) ->
          runTest c (label ++ " haskell block " ++ show i ++ " well-formed")
            (pure (not (null (trimWs blk)) && balanced blk))))
`)
  })
})


export {
  ReadmeExamplesTest
}
