
import { cmp, File, Content } from '@voxgig/sdkgen'


// Emits test/TReadmeExamples.hs — a STRUCTURAL gate over every fenced
// Haskell code block in the three docs that ship Haskell examples:
//   - the root README.md (top-level, multi-language quick start)
//   - the per-language haskell/README.md
//   - the per-language haskell/REFERENCE.md
//
// DESIGN NOTE vs the Python gate (ReadmeExamplesTest_py.ts): the Python
// version parses AND executes every block in a seeded test-mode subprocess.
// A faithful Haskell port would compile every snippet against the generated
// SDK — a throwaway module per block plus a GHC invocation — a large,
// environment-sensitive harness that cannot be authored safely without a build
// to validate it. This gate instead validates that every documented Haskell
// block is PRESENT, non-empty, and STRUCTURALLY well-formed (balanced
// delimiters). Missing docs are tolerated (a run may generate a subset of
// phases), and no blocks found records no failures — so this never breaks the
// shared runner. Upgrading it to a true compile gate is left as a follow-up.
//
// The emitted module exposes `tests :: Counters -> IO ()`; the generated
// SdkGenTests calls it, so it runs inside the standard Runner. The triple
// backtick fence marker is built from its char code (toEnum 96) so this
// component's Haskell source needs no backtick/backslash gymnastics.
const ReadmeExamplesTest = cmp(function ReadmeExamplesTest(props: any) {
  const { target, ctx$: { model } } = props

  const Name = model.const.Name

  File({ name: 'TReadmeExamples.' + target.ext }, () => {
    Content(`-- ${Name} SDK — documentation Haskell-examples structural gate.
--
-- Validates that every fenced Haskell code block in the SDK docs (the root
-- README.md, the per-language README.md, and REFERENCE.md) is present,
-- non-empty, and has balanced delimiters. Missing docs are tolerated (a run
-- may generate a subset of phases), so this gate never breaks the shared
-- runner. See ReadmeExamplesTest_haskell for why this is a structural gate
-- rather than a full compile harness. Generated by @voxgig/sdkgen.

{-# LANGUAGE ScopedTypeVariables #-}

module TReadmeExamples (tests) where

import Control.Exception (SomeException, evaluate, try)
import Control.Monad (forM_)

import Testutil (Counters, runTest)


-- True for the whitespace characters we trim: space, tab, carriage return.
isWs :: Char -> Bool
isWs ch = let n = fromEnum ch in n == 32 || n == 9 || n == 13


-- Trim leading/trailing whitespace from a line.
trimWs :: String -> String
trimWs = f . f
  where f = reverse . dropWhile isWs


-- Read a doc file, tolerating absence (returns "" when missing/unreadable).
readDoc :: FilePath -> IO String
readDoc path = do
  r <- try (do s <- readFile path; _ <- evaluate (length s); pure s)
         :: IO (Either SomeException String)
  pure (either (const "") id r)


-- Extract the body of every fenced Haskell block from markdown. Returns
-- (blocks, allClosed) where allClosed is False when a fence was opened but
-- never closed before EOF — a malformed doc that must fail rather than pass
-- silently on the unterminated block. The fence marker (three backticks) is
-- built from its char code so this source stays backtick-free.
haskellBlocks :: String -> ([String], Bool)
haskellBlocks src = go (lines src)
  where
    fence3 = replicate 3 (toEnum 96 :: Char)
    fenceHs = fence3 ++ "haskell"
    go [] = ([], True)
    go (l : ls)
      | trimWs l == fenceHs =
          case break (\\x -> trimWs x == fence3) ls of
            (blk, [])       -> ([unlines blk], False)
            (blk, _ : rest) -> let (bs, ok) = go rest in (unlines blk : bs, ok)
      | otherwise = go ls


-- Balanced (), [], {} outside of double-quoted string literals, with each
-- closer matching the most-recent opener via a stack (so "([)]" is rejected,
-- not merely counted). The generated snippets never embed an escaped quote
-- inside a string.
balanced :: String -> Bool
balanced = go False []
  where
    go inStr stack [] = not inStr && null stack
    go inStr stack (c : cs)
      | c == '"'                          = go (not inStr) stack cs
      | inStr                             = go inStr stack cs
      | c == '('                          = go inStr (')' : stack) cs
      | c == '['                          = go inStr (']' : stack) cs
      | c == '{'                          = go inStr ('}' : stack) cs
      | c == ')' || c == ']' || c == '}'  =
          case stack of
            (top : rest) | top == c -> go inStr rest cs
            _                        -> False
      | otherwise                         = go inStr stack cs


-- The three documents held to the gate, tagged by human label.
docs :: [(String, FilePath)]
docs =
  [ ("root README", "../README.md")
  , ("${target.name} README", "README.md")
  , ("${target.name} REFERENCE", "REFERENCE.md")
  ]


tests :: Counters -> IO ()
tests c =
  forM_ docs (\\(label, path) -> do
    src <- readDoc path
    let (blocks, closed) = haskellBlocks src
    runTest c (label ++ " haskell fences closed") (pure closed)
    forM_ (zip [1 :: Int ..] blocks) (\\(i, blk) ->
      runTest c (label ++ " haskell block " ++ show i ++ " well-formed")
        (pure (not (null (trimWs blk)) && balanced blk))))
`)
  })
})


export {
  ReadmeExamplesTest
}
