import {
  cmp, each,
  File, Content, Copy, Folder,
} from '@voxgig/sdkgen'

import type {
  ModelEntity
} from '@voxgig/apidef'

import {
  KIT,
  getModelPath
} from '@voxgig/apidef'

import { Package } from './Package_lean'
import { Config } from './Config_lean'
import { Gitignore } from './Gitignore_lean'


// Op name -> generated wrapper. list/load/remove take a match; create takes
// data; update takes both. Any non-standard op falls back to the match+data
// form. Every wrapper delegates to the config-driven SdkRuntime.
function opWrapper(entName: string, opName: string): string {
  const q = `"${entName}"`
  switch (opName) {
    case 'list':
      return `  def list (c m co : Value) : SIO Value := SdkRuntime.opList c ${q} m co\n`
    case 'load':
      return `  def load (c m co : Value) : SIO Value := SdkRuntime.opLoad c ${q} m co\n`
    case 'remove':
      return `  def remove (c m co : Value) : SIO Value := SdkRuntime.opRemove c ${q} m co\n`
    case 'create':
      return `  def create (c d co : Value) : SIO Value := SdkRuntime.opCreate c ${q} d co\n`
    case 'update':
      return `  def update (c m d co : Value) : SIO Value := SdkRuntime.opUpdate c ${q} m d co\n`
    default:
      return `  def ${opName} (c m d co : Value) : SIO Value := SdkRuntime.runOp c ${q} "${opName}" m d co\n`
  }
}


const Main = cmp(async function Main(props: any) {

  const { target } = props
  const { model } = props.ctx$

  const entity: ModelEntity = getModelPath(model, `main.${KIT}.entity`)

  Package({ target })
  Gitignore({})

  // Copy tm/lean verbatim (placeholder substitution applies): the runtime under
  // src/ (VoxgigStruct, Vregex, SdkJson, SdkRuntime), plus LICENSE/VERSION. The
  // per-feature custom-source scaffold under src/feature is excluded.
  Copy({
    from: 'tm/' + target.name,
    exclude: [/src\/feature\//],
    replace: {
      ...props.ctx$.stdrep,
    }
  })

  // Generated modules under src/: the embedded API config and the public
  // client (constructors + one op namespace per entity).
  Folder({ name: 'src' }, () => {

    Config({ target })

    File({ name: 'SdkClient.' + target.ext }, () => {

      let namespaces = ''
      each(entity, (e: any) => {
        // Capitalise the entity name for its op namespace.
        const ns = e.name.charAt(0).toUpperCase() + e.name.slice(1)
        let ops = ''
        each(e.op, (op: any) => { ops += opWrapper(e.name, op.name) })
        namespaces += `namespace ${ns}\n${ops}end ${ns}\n\n`
      })

      Content(`-- ${model.const.Name} SDK public client (generated by @voxgig/sdkgen).
--
-- Constructors (newSdk / testSdk) and one op namespace per entity. Entities are
-- generic: every op delegates to the config-driven SdkRuntime, so the pipeline
-- is identical for every entity and every API.

import VoxgigStruct
import SdkRuntime
import SdkConfig

open VoxgigStruct

namespace Sdk

/-- Construct a live client from an options map (empty map = defaults). -/
def newSdk (options : Value) : SIO Value :=
  SdkRuntime.mkClientV options SdkConfig.configJson

/-- No-argument convenience constructor. -/
def newSdk0 : SIO Value := do newSdk (← emptyMap)

/-- Construct a test-mode client: operations are answered from an in-memory
    store seeded with the entity test data, so no server is needed. -/
def testSdk (seed : Value) (options : Value) : SIO Value :=
  SdkRuntime.mkTestClientV options SdkConfig.configJson seed

/-- Test client with default options. -/
def testSdk0 (seed : Value) : SIO Value := do testSdk seed (← emptyMap)

end Sdk

${namespaces}`)
    })
  })

})


export {
  Main
}
