import {
  Content,
  File,
  cmp,
  packageVersion,
} from '@voxgig/sdkgen'

import type {
  Model,
} from '@voxgig/apidef'

import { leanSecrets, pkgName } from './utility_lean'


// Each runtime module is its own `lean_lib` (Lake globs `<LibName>.lean` from
// srcDir), matching the vendored struct project's layout. The runtime is
// dependency-free (prelude + Std only); the HTTP transport shells to curl.
const LIBS = [
  'Vregex', 'VoxgigStruct', 'SdkJson', 'SdkUtility', 'SdkFeature', 'SdkFeatures', 'SdkRuntime', 'SdkConfig',
  'SdkClient',
]


const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const libBlocks = LIBS.map((n) =>
    `[[lean_lib]]\nname = "${n}"\nsrcDir = "src"\n`).join('\n')

  // THE SECRETS FEATURE, when the model ships it (utility_lean.leanSecrets
  // is the one reading Package_lean and Main_lean share).
  //
  // Each vendored tree is its own Lake srcDir root, so upstream's
  // `import Sekreto.Core` / `import Plugin` / `import SekretoPlugins.X`
  // resolve with NO import rewriting - lean is the one target whose
  // vendored sources carry no adapt at all. The glob spelling is
  // `["X", "X.*"]` (the root and its submodules) rather than `"X.+"`,
  // which an older lake did not read as including the root.
  // SekretoPlugins has no root module ON PURPOSE: upstream's
  // SekretoPlugins.lean is the full-set barrel that imports all ten kinds,
  // which is exactly what a trimmed SDK must not contain (vendored.test.ts
  // pins its absence), so the lib is its submodules alone and each active
  // kind is imported by name from SecretsFeature.lean.
  const secrets = leanSecrets(model, target)

  // The libcurl binding, ONLY with a plugin group on. The plugins reach the
  // network through `@[extern "sekreto_curl_fetch"]` and the clock through
  // `@[extern "sekreto_epoch_seconds"]`; the two C stubs behind them are
  // compiled by `make ffi` (Lake's TOML manifest cannot compile C, and its
  // bundled clang cannot see <curl/curl.h> - see the Makefile), which also
  // writes the ONE response file named here: the objects, the machine's
  // library directories and -lcurl -lssl -lcrypto. A lakefile is static and
  // where libcurl lives is not, so the machine-specific half is computed by
  // make and read by clang through `@file`. Package level, because every
  // test executable imports SdkClient and so links the feature. Without a
  // plugin group nothing here is emitted and the SDK keeps its
  // zero-dependency link (ldd shows no libcurl).
  const ffiBlock = !secrets.ffi ? '' : `
# SECRETS FFI (see Makefile): the plugin groups this model selected bind
# libcurl through src/feature/secrets/ffi/*.c. \`make ffi\` compiles them and
# writes link.rsp; build and run through make, which also sets LEAN_CC.
moreLinkArgs = ["@src/feature/secrets/ffi/link.rsp"]
`

  const secretsBlocks = !secrets.active ? '' : `
# THE SECRETS FEATURE: the vendored voxgig/plugin and sekreto ports, each
# tree its own srcDir root so upstream's imports resolve unchanged; the
# plugin kinds the model selected (SekretoPlugins.*, no barrel); the feature
# over them; and its shipped suite. All of it lives under
# src/feature/secrets/ and test/feature/secrets/, which \`feature add\` trims
# together with this block.
[[lean_lib]]
name = "Plugin"
srcDir = "src/feature/secrets/plugin"
globs = ["Plugin", "Plugin.*"]

[[lean_lib]]
name = "Sekreto"
srcDir = "src/feature/secrets/sekreto"
globs = ["Sekreto", "Sekreto.*"]

[[lean_lib]]
name = "SekretoPlugins"
srcDir = "src/feature/secrets/sekreto/plugins"
globs = ["SekretoPlugins.*"]

[[lean_lib]]
name = "SecretsFeature"
srcDir = "src/feature/secrets"

[[lean_exe]]
name = "secrets"
srcDir = "test/feature/secrets"
root = "TSecrets"
`

  File({ name: 'lakefile.toml' }, () => {
    Content(`# ${model.const.Name} SDK for Lean 4 (generated by @voxgig/sdkgen).
name = "${pkgName(model)}"
version = "${packageVersion(model, target.name)}"
defaultTargets = ["SdkClient"]
${ffiBlock}
${libBlocks}${secretsBlocks}
# The corpus ENGINE: the vendored @voxgig/omni Lean port, source rather than
# a dependency. Its own lean_lib so Lake can find the module, and
# deliberately NOT in defaultTargets: only the test executables import it, so
# \`lake build\` compiles the shipped library without it and nothing a
# consumer installs ever names omni. Lake has no test-scoped dependency, so
# vendoring is what keeps that isolation.
[[lean_lib]]
name = "Omni"
srcDir = "test/vendor/omni"

# The adapter that drives omni's native API with subjects built from this
# SDK's own utilities. Imported by the corpus suites and the smoke test.
[[lean_lib]]
name = "OmniResolver"
srcDir = "test"

[[lean_exe]]
name = "runner"
srcDir = "test"
root = "Runner"

[[lean_exe]]
name = "structcorpus"
srcDir = "test"
root = "StructCorpus"

[[lean_exe]]
name = "primary"
srcDir = "test"
root = "TPrimaryUtility"

[[lean_exe]]
name = "feature"
srcDir = "test"
root = "TFeature"

# Smoke test for the vendored engine itself: a runner that cannot FAIL a bad
# entry would turn every corpus suite vacuously green.
[[lean_exe]]
name = "omnismoke"
srcDir = "test"
root = "OmniSmoke"
`)
  })

  // Pin the toolchain to the version the runtime is developed against.
  File({ name: 'lean-toolchain' }, () => {
    Content(`leanprover/lean4:v4.32.1\n`)
  })
})


export {
  Package
}
