import {
  Content,
  File,
  cmp,
  packageVersion,
} from '@voxgig/sdkgen'

import type {
  Model,
} from '@voxgig/apidef'

import { pkgName } from './utility_lean'


// Each runtime module is its own `lean_lib` (Lake globs `<LibName>.lean` from
// srcDir), matching the vendored struct project's layout. The runtime is
// dependency-free (prelude + Std only); the HTTP transport shells to curl.
const LIBS = [
  'Vregex', 'VoxgigStruct', 'SdkJson', 'SdkUtility', 'SdkFeature', 'SdkFeatures', 'SdkRuntime', 'SdkConfig',
  'SdkClient',
]


const Package = cmp(async function Package(props: any) {
  const ctx$ = props.ctx$
  const target = props.target
  const model: Model = ctx$.model

  const libBlocks = LIBS.map((n) =>
    `[[lean_lib]]\nname = "${n}"\nsrcDir = "src"\n`).join('\n')

  File({ name: 'lakefile.toml' }, () => {
    Content(`# ${model.const.Name} SDK for Lean 4 (generated by @voxgig/sdkgen).
name = "${pkgName(model)}"
version = "${packageVersion(model, target.name)}"
defaultTargets = ["SdkClient"]

${libBlocks}
# The corpus ENGINE: the vendored @voxgig/omni Lean port, source rather than
# a dependency. Its own lean_lib so Lake can find the module, and
# deliberately NOT in defaultTargets: only the test executables import it, so
# \`lake build\` compiles the shipped library without it and nothing a
# consumer installs ever names omni. Lake has no test-scoped dependency, so
# vendoring is what keeps that isolation.
[[lean_lib]]
name = "Omni"
srcDir = "test/vendor/omni"

# The adapter that drives omni's native API with subjects built from this
# SDK's own utilities. Imported by the corpus suites and the smoke test.
[[lean_lib]]
name = "OmniResolver"
srcDir = "test"

[[lean_exe]]
name = "runner"
srcDir = "test"
root = "Runner"

[[lean_exe]]
name = "structcorpus"
srcDir = "test"
root = "StructCorpus"

[[lean_exe]]
name = "primary"
srcDir = "test"
root = "TPrimaryUtility"

[[lean_exe]]
name = "feature"
srcDir = "test"
root = "TFeature"

# Smoke test for the vendored engine itself: a runner that cannot FAIL a bad
# entry would turn every corpus suite vacuously green.
[[lean_exe]]
name = "omnismoke"
srcDir = "test"
root = "OmniSmoke"
`)
  })

  // Pin the toolchain to the version the runtime is developed against.
  File({ name: 'lean-toolchain' }, () => {
    Content(`leanprover/lean4:v4.32.1\n`)
  })
})


export {
  Package
}
